[package]
name = "rust-101"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
tokio = { version="1.39", features=["full"] }

serde = { version="1.0", features=["derive"] }
serde_json = "1.0"
serde_cbor = "0.11"
